name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: image_tag
          path: .

      - name: Provide image tag as terraform variable
        id: export_image_tag
        run: |
          IMAGE_TAG=$(cat ./image_tag.txt)
          echo "TF_VAR_image_tag=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init -backend-config=s3.tfbackend -input=false
        working-directory: infrastructure

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: infrastructure