name: Code Tests

# on:
#   pull_request:

jobs:
  application:
    name: application-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r application/requirements.txt
          pip install pylint bandit

      - name: Run Pylint
        run: |
          pylint application/app.py

      - name: Run Bandit
        run: |
          bandit -r application -c .bandit.yaml

  infrastructure:
    name: infrastructure-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run terraform fmt
        run: |
          terraform fmt -recursive
        working-directory: infrastructure

      - name: Run TFLint
        run: |
          tflint --init
          tflint
        working-directory: infrastructure

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: infrastructure